version = 0.1
[default.deploy.parameters]
stack_name = "url-compressor"
resolve_s3 = true
s3_prefix = "url-compressor"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
