AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  API for compress URL for QR code

Resources:
  CompressUrlFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: .
      Handler: compress-url
      Runtime: provided.al2023
      Architectures: [arm64]
      FunctionUrlConfig:
        AuthType: NONE
      Environment:
        Variables:
          COMPRESSOR_HOSTNAME: "c.shogo82148.com"

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: lambda
            DomainName: !Select [
                2, # HACK for removing https://
                !Split ["/", !GetAtt CompressUrlFunctionUrl.FunctionUrl],
              ]
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
        DefaultCacheBehavior:
          CachePolicyId: !GetAtt AllQueryStringPolicy.Id
          ViewerProtocolPolicy: redirect-to-https
          TargetOriginId: lambda
        Enabled: true
        IPV6Enabled: true
        HttpVersion: http2and3
        Aliases:
          - "c.shogo82148.com"
        ViewerCertificate:
          SslSupportMethod: sni-only
          # for shogo82148.com
          AcmCertificateArn: arn:aws:acm:us-east-1:445285296882:certificate/6d4dadf8-7d77-46ad-b6b9-e282c495a6e9
          MinimumProtocolVersion: TLSv1.2_2021

  AllQueryStringPolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: AllQueryStringPolicy
        DefaultTTL: 60
        MaxTTL: 60
        MinTTL: 1
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingBrotli: true
          EnableAcceptEncodingGzip: true
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: all

  RecordSetA:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: "shogo82148.com."
      Name: "c.shogo82148.com"
      Type: A
      AliasTarget:
        DNSName: !GetAtt Distribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2 # hosted zone ID for cloudfront.net

  RecordSetAAAA:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: "shogo82148.com."
      Name: "c.shogo82148.com"
      Type: AAAA
      AliasTarget:
        DNSName: !GetAtt Distribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2 # hosted zone ID for cloudfront.net
