AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  API for compress URL for QR code

Resources:
  CompressUrlFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: .
      Handler: compress-url
      Runtime: provided.al2023
      Architectures: [arm64]
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            ApiId: !Ref CompressUrlApi

  CompressUrlApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Description: API for compress URL for QR code
