AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  API for compress URL for QR code

Resources:
  CompressUrlFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: .
      Handler: compress-url
      Runtime: provided.al2023
      Architectures: [arm64]
      FunctionUrlConfig:
        AuthType: NONE

  # RecordSet:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     HostedZoneName: "shogo82148.com."
  #     Name: "c.shogo82148.com"
  #     Type: A
  #     AliasTarget:
  #       DNSName: !GetAtt ApiGatewayDomainNameV24c58e33fd3.RegionalDomainName
  #       HostedZoneId: !GetAtt ApiGatewayDomainNameV24c58e33fd3.RegionalHostedZoneId

  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: "c.shogo82148.com"
      ValidationMethod: "DNS"
      DomainValidationOptions:
        - DomainName: "c.shogo82148.com"
          HostedZoneId: Z1TR8BQNS8S1I7
